### ISSUE TITLE
Rammed filament interferes with blob formation

### ISSUE THREAD

**Issue by vintagepc** [vintagepc/RPM-Post#5]
Filament ejected during the ramming sequence cools while the toolchange is happening. This appears to interfere with blob formation.

**Comment by bynnek** [comment]
I've noticed this one too.  I haven't tried your branch for the test fix yet though.  Looks like you also changed the way the fan was invoked during purging?  Was this to address the fan staying on during a second purge rather than just during the cool / hold time?

**Comment by vintagepc** [comment]
Yes, it should also address the fan timing being incorrect during multiple purges.

**Comment by bynnek** [comment]
This one wasn't affecting me too much before but I've started have longer prints jam in the purge bucket because of this.  Was your fix you were testing working ok?  I never tried this branch as I hopped on the other one you made for the retraction issue.

**Comment by bynnek** [comment]
The new ramming / cooling behavior works a lot better!  Looks like your merge of the master into this branch missed the peek ahead stuff though for the TC retract bug.  It was easy enough to paste in myself but wanted to give you a heads up.

**Comment by vintagepc** [comment]
well nuts, I probably merged a stale local master instead of origin/master. But since it seems to be working for you, I'll merge this up to master :-)
Thanks for your time testing this stuff!

**Comment by bynnek** [comment]
After a bit more testing with this, I found something that probably doesn't require a change to the code but is worth mentioning.  When I use the same ramming / tip shaping settings and print either with the RPM script or the old fashion wiper tower way, I get different results.  The RPM code is leaving me with some super thing but super long tails on my filaments.  The old fashioned way isn't doing that.  I can likely just tweak the ramming settings a bit but I thought it was worth mentioning.  It does "sound" the same, as in the stages and speeds the filament moves sound about the same.  I haven't actually compared Gcode yet, but I'll give that a check next.

**Comment by bynnek** [comment]
Ah, I see a note in the code about this.  Not sure if this is the cause, but its the only real difference I see right now.  Looks like you already identified it.  

![image](https://user-images.githubusercontent.com/48171493/76184387-fd386700-6188-11ea-9e6a-e0cd6381a906.png)

**Comment by vintagepc** [comment]
Hmmm, thanks for the info. The comment isn't related to this, it's more of a general note that the values are essentially expected to differ. 

I'll do some slicing and comparing of pre/post ramming to see if I can ID what is different.

**Comment by vintagepc** [comment]
Just to clarify, Is this issue new to this particular ramming purge sequence mod, or has it always done that with the RPM code?

**Comment by bynnek** [comment]
I am not sure, I suspect it maybe has always been there so it might not be applicable to this issue.

**Comment by vintagepc** [comment]
OK. I'll turn it into a separate issue, #13
