### ISSUE TITLE
Add current bump to motor during bucket operation

### ISSUE THREAD

**Issue by bynnek** [vintagepc/RPM-Post#7]
My MK2.5 stalls out sometimes when triggering the purge bucket due to resistance in the purge unit.  Some of the other folks using this setup temporarily increase the current via a m907 command temporarily (say from 300 to 450 or higher).  It would be cool if you could add this to the script.  Maybe similar to your bucket position command we could add a line for nominal and high current values in a similar fashion (in the start of gcode section).  

I've already taken a few springs off the purge mechanism but I think the MK2.5 not having the same stepper controllers as the MK3 leaves it a bit underpowered.

**Comment by vintagepc** [comment]
So the good news is I don't think I actually have to alter the code- you can do this in the PS 'custom toolchange gcode' section by placing your preferred current settings before/after the T command. The gcode inserts itself specifically around that, so anything before/after is left alone :-)

**Comment by bynnek** [comment]
Oh, yeah, you are right!  That would be a convenient place to put it.

**Comment by bynnek** [comment]
Looks like that trick is indeed putting it in the right spots in the gcode.  I have't actually run the code but looks like this should be good.
