### ISSUE TITLE
Incorrect TC retract amount

### ISSUE THREAD

**Issue by bynnek** [vintagepc/RPM-Post#8]
Looks like at the end of a purge, you invoke the extruder to retract by the value of "retract_length_toolchange".  However, when the extruder goes to start printing again, it only re-primes the nozzle to the value of "retract_length".  This causes the printer to print air for a little bit till the filament reaches the nozzle.  

; retract_length = 0.8,0.8,0.8,0.8,0.8
; retract_length_toolchange = 3,3,3,3,3

I'm not sure why the original gcode is not using the "retract_length_toolchange" but it seems like the easiest fix would be to use the "retract_length" value instead.

**Comment by bynnek** [comment]
Upon looking into this more, sometimes PSlicer uses the retract_length and sometimes retract_length_toochange...  I'm not sure why it uses one of the other.   Seems like the very first tool change it is using regular retract and on the 2nd, using toolchange.

**Comment by vintagepc** [comment]
Well, that explains why I was over-de-retracting when I originally used retract_length, and then changed it to use toolchange retract when I inspected the gcode as to why. 

There must be some kind of logic to what PS is doing... this'll be fun to debug. /s

**Comment by vintagepc** [comment]
aha, I think this is skirt related. I see "regular" deretracts on skirt layers following a toolchange, and normal toolchange_retracts if there is no skirt. 
Is that consistent with your observations? Can you attach the offending gcode?

**Comment by bynnek** [comment]
Hmm, I have skirts disabled on my prints but I'm still having the issue.  Attached is the pre and post processed gcode (same as the other issue I opened that night). 
[MMUPurgeCal.zip](https://github.com/vintagepc/RPM-Post/files/4178948/MMUPurgeCal.zip)

I seem to remember there being an issue on the PSlicer board regarding this similar issue for folks when using the old tower method...  perhaps it was this one:
https://github.com/prusa3d/PrusaSlicer/issues/2834

**Comment by vintagepc** [comment]
Hmm... I am running the 2.2 alpha; all of my de-retracts seem to line up except the skirt layers. 
Thanks for the gcode submission. I'll review it in the next few days.

**Comment by vintagepc** [comment]
So your test object only has ~2 toolchanges. Could you slice something with more to determine if this is a persistent issue with your setup or if it only afffects the first few layers like I see with my test cases?

For the record, here are the retractions I pulled out:
First one, this one is weird and the problem child
G1 E-3.0000 F2100.0000; TC retract
G1 E-0.80000
G1 E0.80000 F2100.00000

Second one - functions as expected.
G1 E-3.0000 F2100.0000; TC retract
G1 E3.00000 F2100.00000

**Comment by bynnek** [comment]
Yeah, I'll add some more toolchanges tonight and report back.

**Comment by bynnek** [comment]
I tried turning the wipe tower back on.  Seems like when that is enabled, the behavior is different. It uses the TC retract value when leaving the print and traveling to the wipe tower.  It retracts and un-retracts by the time it reaches the tower.  After doing the purge on the tower, it just does a normal retract to un-retract as it goes back to the print.  I couldn't actually find anywhere where this one had an incorrect retract length...  

Also, is the 2.2mm retract before the toolchange in the RPM script intentional?  I don't see an un-retract for it but I don't suppose that really matters anyways as it goes straight into the cooling moves from there (after moving to the purge area).

**Comment by vintagepc** [comment]
The 2.2 is not my gcode, that comes from PS (you can see it's before the "end gcode" for the filament. All my script does is expand the T command into the sequence of RPM moves.

In my own files, that's not 2.2 but 0.2, seems to be a mashup of retraction and z lift for the extruder.

**Comment by bynnek** [comment]
I'm not sure if fixing the bug in 2834 is going to resolve this as I can't replicated the bad retractions with the purge tower on.  A crappy patch might be to check for the first E movement after the end of the purge bucket maneuver and see if it matches the toolchange retraction or not.  If it doesn't, the format of the error seems regular enough that you could modify the last de-retraction in that set to match the tool change value.

**Comment by vintagepc** [comment]
Yeah, we may not have much choice; fortunately it's not overly difficult to "peek ahead" and determine if the bug is present. I may have some time this weekend, we'll see how it pans out.

**Comment by vintagepc** [comment]
I've just pushed up a branch with a candidate detection/workaround. Do you have some time to try it?

**Comment by bynnek** [comment]
Sorry, been traveling for work.  I'll try later tonight or tomorrow.  Thanks for working on this!

**Comment by vintagepc** [comment]
No worries :-)

**Comment by bynnek** [comment]
So far it looks like it is working correctly.  I only tried a few slices but seems to catch all the faulty ones.    Nice work!
