### ISSUE TITLE
maxrate for purging incorrectly calculated

### ISSUE THREAD

**Issue by bynnek** [vintagepc/RPM-Post#9]
the "maxrate" variable is being calculated to be zero incorrectly which then causes the gcode to extrude too slowly during the purge.  I think this is partially due to line 114 of the code just setting the diameter to zero rather than pulling it from the gcode.  The other part seems to be that the max_vol_rate is not being calculated correctly either.  It's coming out as zero.  From what I can tell, it is pulling that correctly from the gcode because filament_volumetric_settings has all the right values, but when it performs "max_vol_rate": min(float(filament_volumetric_settings[tool]),PRINTER_MAX_VOLUMETRIC) it comes up with zero.

**Comment by vintagepc** [comment]
Line 114 should be inconsequential, we stuff those values at line 148 instead. That could definitely be cleaned and moved up. Probably just some unintentional cruft that's built up over the various iterations. 

As for the issue, can you attach the offending gcode (both pre and post-processed)? I stopped in debug mode and max_vol_rate is being calculated correctly:
![image](https://user-images.githubusercontent.com/53943260/74102237-853a3b00-4b0f-11ea-91f3-9c43d47b3fab.png)

**Comment by vintagepc** [comment]
Also, for me the maxrates have been coming out reasonably - they're in the right ballpark as I experimented with them during earlier bucket iterations and found I could not go much higher as I'd get extruder skipping.

**Comment by bynnek** [comment]
Attached is the pre and post processed gcode:
[MMUPurgeCal.zip](https://github.com/vintagepc/RPM-Post/files/4178939/MMUPurgeCal.zip)

I don't think it formats stuff differently in PSlicer but its worth noting I have a MK2.5s and not a MK3s.

**Comment by vintagepc** [comment]
The issue is that your printer's max volumetric speed is not configured. It is set to 0 in your input file.

Line 1135:
`; max_volumetric_speed = 0`

It's found under print settings -> speed -> autospeed.

That said, I've added a warning/fallback for this case.

**Comment by bynnek** [comment]
Oh, interesting.  I was expecting it to pull from "filament_max_volumetric_speed" rather than the old single extruder "max_volumetric_speed" variable.  It might be better to pull from the filament one as that one is much more convenient (don't have to set it to a new value every time you print with a different filament).

**Comment by vintagepc** [comment]
There's a hierarchy of inheritance here, both are used and we take the minimum of all. That way, you can, for example, specify filament max rates in your filament profile, but throttle back the print preference to automatically limit speed below that for a particular print profile. We just weren't expecting to see 0 for the print profile one.

**Comment by bynnek** [comment]
Gotcha, that makes sense
